-- 1. Enable PostGIS Extension
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. Create Primary Elevation Table (Baseline)
CREATE TABLE IF NOT EXISTS elevation_primary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_index TEXT UNIQUE,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    elevation DOUBLE PRECISION NOT NULL,
    geom GEOMETRY(Point, 4326),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Secondary Elevation Table (Current/Satellite)
CREATE TABLE IF NOT EXISTS elevation_secondary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_index TEXT UNIQUE,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    elevation DOUBLE PRECISION NOT NULL,
    geom GEOMETRY(Point, 4326),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.1 Create River Data Table
CREATE TABLE IF NOT EXISTS river_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_index TEXT,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    elevation DOUBLE PRECISION NOT NULL,
    geom GEOMETRY(Point, 4326),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Spatial Indices for Fast Mapping
CREATE INDEX IF NOT EXISTS idx_elevation_primary_geom ON elevation_primary USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_elevation_secondary_geom ON elevation_secondary USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_river_data_geom ON river_data USING GIST (geom);

-- 4.1 Auto-populate geom column from lat/lng
CREATE OR REPLACE FUNCTION populate_elevation_geom()
RETURNS TRIGGER AS $$
BEGIN
    NEW.geom := ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_populate_elevation_primary_geom
BEFORE INSERT OR UPDATE ON elevation_primary
FOR EACH ROW EXECUTE FUNCTION populate_elevation_geom();

CREATE TRIGGER trg_populate_elevation_secondary_geom
BEFORE INSERT OR UPDATE ON elevation_secondary
FOR EACH ROW EXECUTE FUNCTION populate_elevation_geom();

CREATE TRIGGER trg_populate_river_data_geom
BEFORE INSERT OR UPDATE ON river_data
FOR EACH ROW EXECUTE FUNCTION populate_elevation_geom();

-- 5. Create Flood Risk SQL View (Refined GIS Logic)
-- Logic: Uses Spatial Join (ST_DWithin) to correlate source A and source B points
-- Adds a deterministic ROW_NUMBER as 'id' for stable frontend rendering
DROP VIEW IF EXISTS flood_risk_view;

CREATE VIEW flood_risk_view AS
SELECT 
    ROW_NUMBER() OVER () as id, -- Guaranteed unique identifier for React keys
    p.system_index as baseline_index,
    s.system_index as current_index,
    p.latitude,
    p.longitude,
    p.elevation as elevation_baseline,
    s.elevation as elevation_current,
    (p.elevation - s.elevation) as elevation_delta,
    CASE 
        WHEN s.elevation < 19.0 THEN 'High Risk (Red)'
        WHEN s.elevation >= 19.0 AND s.elevation <= 21.0 THEN 'Moderate Risk (Yellow)'
        ELSE 'Safe Zone (Green)'
    END as risk_status,
    CASE 
        WHEN (p.elevation - s.elevation) > 0.5 THEN 'Worsened'
        WHEN (p.elevation - s.elevation) < -0.5 THEN 'Improved'
        ELSE 'Stable'
    END as change_analysis,
    p.geom
FROM elevation_primary p
INNER JOIN elevation_secondary s 
ON ST_DWithin(p.geom, s.geom, 0.0001);

-- 6. RPC Function for Aggregated Analytics
CREATE OR REPLACE FUNCTION get_risk_summary()
RETURNS TABLE (status TEXT, count BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT risk_status, COUNT(*)
    FROM flood_risk_view
    GROUP BY risk_status;
END;
$$ LANGUAGE plpgsql;

-- 7. High-Performance Clear RPC (TRUNCATE)
-- Uses SECURITY DEFINER and a fixed search_path for permission stability
CREATE OR REPLACE FUNCTION clear_elevation_data()
RETURNS void AS $$
BEGIN
    TRUNCATE TABLE elevation_primary CASCADE;
    TRUNCATE TABLE elevation_secondary CASCADE;
    TRUNCATE TABLE river_data CASCADE;
END;
$$ LANGUAGE plpgsql 
SECURITY DEFINER
SET search_path = public;

-- 8. Advanced Spatial Stats RPC
CREATE OR REPLACE FUNCTION get_spatial_stats()
RETURNS TABLE (
    total_elevation_points BIGINT,
    total_river_points BIGINT,
    analyzed_area_km2 DOUBLE PRECISION
) AS $$
DECLARE
    all_points_geom GEOMETRY;
BEGIN
    -- Combine all points into one collection for hull calculation
    SELECT ST_Collect(geom) INTO all_points_geom FROM (
        SELECT geom FROM (SELECT geom FROM elevation_primary LIMIT 5000) p1
        UNION ALL
        SELECT geom FROM (SELECT geom FROM elevation_secondary LIMIT 5000) p2
        UNION ALL
        SELECT geom FROM river_data
    ) sub;

    RETURN QUERY
    SELECT 
        (SELECT COUNT(*) FROM elevation_primary) + (SELECT COUNT(*) FROM elevation_secondary) as total_elevation_points,
        (SELECT COUNT(*) FROM river_data) as total_river_points,
        COALESCE(ST_Area(ST_ConvexHull(all_points_geom)::geography) / 1000000.0, 0.0) as analyzed_area_km2;
END;
$$ LANGUAGE plpgsql;

-- 8. Permissions
GRANT EXECUTE ON FUNCTION clear_elevation_data() TO anon;
GRANT EXECUTE ON FUNCTION clear_elevation_data() TO authenticated;
GRANT EXECUTE ON FUNCTION clear_elevation_data() TO service_role;
GRANT EXECUTE ON FUNCTION get_spatial_stats() TO anon;
GRANT EXECUTE ON FUNCTION get_spatial_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION get_spatial_stats() TO service_role;
