-- 1. Enable PostGIS Extension
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. Create Land Data Table (Static Elevation)
CREATE TABLE IF NOT EXISTS land_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_index TEXT UNIQUE,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    elevation DOUBLE PRECISION NOT NULL,
    geom GEOMETRY(Point, 4326),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create River Baseline Table (Historical)
CREATE TABLE IF NOT EXISTS river_baseline (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_index TEXT,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    elevation DOUBLE PRECISION NOT NULL,
    geom GEOMETRY(Point, 4326),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.1 Create River Current Table (Satellite/Latest)
CREATE TABLE IF NOT EXISTS river_current (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_index TEXT,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    elevation DOUBLE PRECISION NOT NULL,
    geom GEOMETRY(Point, 4326),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Spatial Indices for Fast Mapping
CREATE INDEX IF NOT EXISTS idx_land_data_geom ON land_data USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_river_baseline_geom ON river_baseline USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_river_current_geom ON river_current USING GIST (geom);

-- 4.1 Auto-populate geom column from lat/lng
CREATE OR REPLACE FUNCTION populate_elevation_geom()
RETURNS TRIGGER AS $$
BEGIN
    NEW.geom := ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_populate_land_data_geom BEFORE INSERT OR UPDATE ON land_data FOR EACH ROW EXECUTE FUNCTION populate_elevation_geom();
CREATE TRIGGER trg_populate_river_baseline_geom BEFORE INSERT OR UPDATE ON river_baseline FOR EACH ROW EXECUTE FUNCTION populate_elevation_geom();
CREATE TRIGGER trg_populate_river_current_geom BEFORE INSERT OR UPDATE ON river_current FOR EACH ROW EXECUTE FUNCTION populate_elevation_geom();

-- 5. Create Integrated Flood Risk View (GIS Logic)
-- Concept: Every land point calculates its risk relative to the nearest river nodes
DROP VIEW IF EXISTS flood_risk_view;

CREATE VIEW flood_risk_view AS
SELECT 
    l.id,
    l.system_index as baseline_index,
    'Current' as current_index,
    l.latitude,
    l.longitude,
    l.elevation as elevation_baseline, -- Static Land Elevation
    COALESCE(rc.elevation, l.elevation) as elevation_current,  -- Nearest Current River Elevation
    (l.elevation - COALESCE(rc.elevation, l.elevation)) as river_clearance,
    (COALESCE(rb.elevation, rc.elevation, l.elevation) - COALESCE(rc.elevation, l.elevation)) as elevation_delta, -- Temporal change in river level
    COALESCE(ST_Distance(l.geom::geography, rc.geom::geography), 0.0) as distance_to_river_m,
    CASE 
        WHEN rc.id IS NULL THEN 'No Data'
        WHEN (l.elevation - rc.elevation) < 1.0 THEN 'High Risk (Red)'
        WHEN (l.elevation - rc.elevation) >= 1.0 AND (l.elevation - rc.elevation) <= 3.0 THEN 'Moderate Risk (Yellow)'
        ELSE 'Safe Zone (Green)'
    END as risk_status,
    CASE 
        WHEN rb.id IS NULL OR rc.id IS NULL THEN 'Stable'
        WHEN (rb.elevation - rc.elevation) > 0.5 THEN 'Worsened'
        WHEN (rb.elevation - rc.elevation) < -0.5 THEN 'Improved'
        ELSE 'Stable'
    END as change_analysis,
    l.geom
FROM land_data l
LEFT JOIN LATERAL (
    SELECT id, elevation, geom
    FROM river_current
    ORDER BY l.geom <-> geom
    LIMIT 1
) rc ON TRUE
LEFT JOIN LATERAL (
    SELECT id, elevation
    FROM river_baseline
    ORDER BY l.geom <-> geom
    LIMIT 1
) rb ON TRUE;

-- 6. RPC Function for Aggregated Analytics
CREATE OR REPLACE FUNCTION get_risk_summary()
RETURNS TABLE (status TEXT, count BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT risk_status, COUNT(*)
    FROM flood_risk_view
    GROUP BY risk_status;
END;
$$ LANGUAGE plpgsql;

-- 7. High-Performance Clear RPC (TRUNCATE)
CREATE OR REPLACE FUNCTION clear_elevation_data()
RETURNS void AS $$
BEGIN
    TRUNCATE TABLE land_data CASCADE;
    TRUNCATE TABLE river_baseline CASCADE;
    TRUNCATE TABLE river_current CASCADE;
END;
$$ LANGUAGE plpgsql 
SECURITY DEFINER
SET search_path = public;

-- 8. Advanced Spatial Stats RPC
CREATE OR REPLACE FUNCTION get_spatial_stats()
RETURNS TABLE (
    total_elevation_points BIGINT,
    total_river_points BIGINT,
    analyzed_area_km2 DOUBLE PRECISION
) AS $$
DECLARE
    all_points_geom GEOMETRY;
BEGIN
    SELECT ST_Collect(geom) INTO all_points_geom FROM (
        SELECT geom FROM (SELECT geom FROM land_data LIMIT 5000) p1
        UNION ALL
        SELECT geom FROM river_baseline
        UNION ALL
        SELECT geom FROM river_current
    ) sub;

    RETURN QUERY
    SELECT 
        (SELECT COUNT(*) FROM land_data) as total_elevation_points,
        (SELECT COUNT(*) FROM river_current) as total_river_points,
        COALESCE(ST_Area(ST_ConvexHull(all_points_geom)::geography) / 1000000.0, 0.0) as analyzed_area_km2;
END;
$$ LANGUAGE plpgsql;

-- 9. Permissions
GRANT EXECUTE ON FUNCTION clear_elevation_data() TO anon;
GRANT EXECUTE ON FUNCTION clear_elevation_data() TO authenticated;
GRANT EXECUTE ON FUNCTION clear_elevation_data() TO service_role;
GRANT EXECUTE ON FUNCTION get_spatial_stats() TO anon;
GRANT EXECUTE ON FUNCTION get_spatial_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION get_spatial_stats() TO service_role;

-- 10. River Comparison RPC for Analytics
CREATE OR REPLACE FUNCTION get_river_comparison()
RETURNS TABLE (
    name TEXT,
    baseline DOUBLE PRECISION,
    current DOUBLE PRECISION
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COALESCE(rc.system_index, 'Point ' || rc.id) as name,
        rb.elevation as baseline,
        rc.elevation as current
    FROM river_current rc
    JOIN river_baseline rb ON rc.system_index = rb.system_index
    ORDER BY rc.id ASC
    LIMIT 15;
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION get_river_comparison() TO anon;
GRANT EXECUTE ON FUNCTION get_river_comparison() TO authenticated;
GRANT EXECUTE ON FUNCTION get_river_comparison() TO service_role;
